apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  namespace: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
        - name: dvwa
          image: vulnerables/web-dvwa:latest
          ports:
            - containerPort: 80
          stdin: true
          tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  namespace: dvwa
spec:
  selector:
    app: dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
